// Exhaustive length-ten boundary proof. C++17, standard library only.
// Enumerates fixed-{1,2} swap orbits, then proves protection by finding
// bad-free cosets of the subspace generated by a port matching.
#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <utility>
#include <vector>
using namespace std;

using Word = array<int, 10>;
const int AUX[] = {6, 10, 18, 12, 20, 24};
struct Matching { vector<pair<int, int>> pairs; vector<int> span; };
vector<Matching> matchings[11];

void build_matchings(int size, int mask, vector<pair<int, int>>& pairs) {
    if (!mask) {
        Matching m{pairs, {0}};
        for (auto [i, j] : pairs) {
            int n = m.span.size();
            for (int k = 0; k < n; ++k)
                m.span.push_back(m.span[k] ^ (1 << i) ^ (1 << j));
        }
        matchings[size].push_back(m);
        return;
    }
    int i = __builtin_ctz(unsigned(mask));
    mask ^= 1 << i;
    for (int j = i + 1; j < size; ++j) if (mask >> j & 1) {
        pairs.emplace_back(i, j);
        build_matchings(size, mask ^ (1 << j), pairs);
        pairs.pop_back();
    }
}

bool rejected(const Word& word, int marked) {
    int prefix = 0;
    uint32_t seen = 0;
    for (int i = 0; i < 10; ++i) {
        if (marked >> i & 1) seen |= uint32_t(1) << prefix;
        prefix ^= word[i];
    }
    if (prefix) abort();
    return __builtin_popcount(seen) == 8;
}

bool has_matching(int mask, const array<int, 10>& adjacent) {
    if (!mask) return true;
    int i = __builtin_ctz(unsigned(mask));
    int rest = mask ^ (1 << i), choices = adjacent[i] & rest;
    while (choices) {
        int j = __builtin_ctz(unsigned(choices));
        choices ^= 1 << j;
        if (has_matching(rest ^ (1 << j), adjacent)) return true;
    }
    return false;
}

bool forces_escape(Word& word, int swap, int marked) {
    int affected = 0;
    array<int, 10> adjacent{};
    for (int i = 0; i < 10; ++i)
        if (__builtin_popcount(unsigned(word[i] & swap)) == 1) affected |= 1 << i;
    for (int i = 0; i < 10; ++i) if (affected >> i & 1)
        for (int j = i + 1; j < 10; ++j) if (affected >> j & 1) {
            word[i] ^= swap; word[j] ^= swap;
            bool bad = rejected(word, marked);
            word[i] ^= swap; word[j] ^= swap;
            if (bad) { adjacent[i] |= 1 << j; adjacent[j] |= 1 << i; }
        }
    return !has_matching(affected, adjacent);
}

struct Counts {
    long long groups = 0, states = 0, bad = 0, threats = 0, good_checked = 0;
    array<long long, 7> forcing{};
};

void audit_group(const Word& key, int marked, Counts& counts) {
    int sum = 0;
    vector<int> active;
    for (int i = 0; i < 10; ++i) {
        sum ^= key[i];
        if (__builtin_popcount(unsigned(key[i] & 6)) == 1) active.push_back(i);
    }
    if (sum != 0 && sum != 6) return;
    int size = active.size(), parity = sum == 6, limit = 1 << size;
    if (size % 2 || (!size && sum)) return;
    ++counts.groups;
    vector<char> bad(limit), remaining(limit);
    int bad_count = 0;
    for (int bits = 0; bits < limit; ++bits)
        if (__builtin_parity(unsigned(bits)) == parity) {
            ++counts.states;
            Word word = key;
            for (int j = 0; j < size; ++j) if (bits >> j & 1) word[active[j]] ^= 6;
            if (rejected(word, marked)) {
                bad[bits] = 1; ++bad_count; ++counts.bad;
                int choices = 0;
                for (int swap : AUX) choices += forces_escape(word, swap, marked);
                ++counts.forcing[choices];
                if (!choices) { cerr << "Escape failed\n"; exit(2); }
            } else remaining[bits] = 1;
        }
    if (!bad_count) return; // Every matching in a bad-free orbit is protected.
    ++counts.threats;
    int todo = (size ? limit / 2 : 1) - bad_count;
    counts.good_checked += todo;
    for (const auto& matching : matchings[size]) {
        vector<char> visited(limit);
        for (int bits = 0; bits < limit; ++bits) if (remaining[bits] && !visited[bits]) {
            bool safe = true;
            for (int s : matching.span) {
                visited[bits ^ s] = 1;
                if (bad[bits ^ s]) safe = false;
            }
            if (safe) for (int s : matching.span) if (remaining[bits ^ s]) {
                remaining[bits ^ s] = 0; --todo;
            }
        }
        if (!todo) break;
    }
    if (todo) { cerr << "Protection failed\n"; exit(3); }
}

void enumerate_keys(int position, Word& key, int marked, int odd, Counts& counts) {
    if (position == 10) { audit_group(key, marked, counts); return; }
    bool distinguished = ((odd >> position) ^ (odd >> ((position + 1) % 10))) & 1;
    // Canonical representatives of the {1,2}-swap orbits of each alphabet.
    vector<int> alphabet = distinguished ? vector<int>{3, 9, 17} : vector<int>{6, 10, 18, 24};
    for (int pair : alphabet) {
        key[position] = pair;
        enumerate_keys(position + 1, key, marked, odd, counts);
    }
}

int main() {
    for (int size = 0; size <= 10; size += 2) {
        vector<pair<int, int>> pairs;
        build_matchings(size, (1 << size) - 1, pairs);
    }
    vector<pair<int, int>> profiles = {{1023, 0}, {1022, 0}, {1022, 1}};
    for (int distance = 1; distance <= 5; ++distance) {
        int marked = 1023 ^ 1 ^ (1 << distance);
        for (int odd : {0, 1, 1 | (1 << distance)}) profiles.emplace_back(marked, odd);
    }
    for (auto [marked, odd] : profiles) {
        Counts counts;
        Word key{};
        enumerate_keys(0, key, marked, odd, counts);
        cout << marked << ' ' << odd << ' ' << counts.groups << ' ' << counts.states
             << ' ' << counts.bad << ' ' << counts.threats << ' ' << counts.good_checked;
        for (auto n : counts.forcing) cout << ' ' << n;
        cout << endl;
    }
}
